In [5]:
import os
import numpy as np
import cv2
from tensorflow.keras.utils import to_categorical

from keras.layers import Input, Dense
from keras.models import Model

In [6]:
is_init = False
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir():
    if i.split(".")[-1] == "npy" and not(i.split(".")[0]=="labels"):
        if not(is_init):
            is_init = True
            X = np.load(i)
            size = X.shape[0]
            y = np.array([i.split('.')[0]]*size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(i)))
            y = np.concatenate((y, np.array([i.split('.')[0]]*size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c
        c+=1

for i in range(y.shape[0]):
    y[i, 0] = dictionary[y[i,0]]
y = np.array(y, dtype="int32")

y = to_categorical(y)

In [8]:
X_new = X.copy()
y_new = y.copy()
counter = 0

cnt = np.arange(X.shape[0])
np.random.shuffle(cnt)

for i in cnt:
    X_new[counter] = X[i]
    y_new[counter] = y[i]
    counter +=1

ip = Input(shape=(X_new.shape[1]))

m = Dense(512, activation="relu")(ip)
m = Dense(256, activation="relu")(m)

op = Dense(y_new.shape[1], activation="softmax")(m)

model = Model(inputs=ip, outputs=op)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['acc'])

model.fit(X_new, y_new, epochs = 50)

model.save("model.h5")
np.save("labels.npy", np.array(label))

{'angry': 0, 'bored': 1, 'calm': 2, 'disgust': 3, 'happy': 4, 'indifferent': 5, 'joyful': 6, 'nervous': 7, 'sad': 8, 'surprise': 9}
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
Epoch 1/50
32/32 [==============================] - 2s 10ms/step - loss: 2.2156 - acc: 0.1960
Epoch 2/50
32/32 [==============================] - 0s 6ms/step - loss: 1.7486 - acc: 0.4210
Epoch 3/50
32/32 [==============================] - 0s 7ms/step - loss: 1.2635 - acc: 0.6220
Epoch 4/50
32/32 [==============================] - 0s 6ms/step - loss: 0.9273 - acc: 0.7470
Epoch 5/50
32/32 [==============================] - 0s 6ms/step - loss: 0.7297 - acc: 0.8010
Epoch 6/50
32/32 [==============================] - 0s 7ms/step - loss: 0.5855 - acc: 0.8370
Epoch 7/50
32/32 [==============================] - 0s 7ms/step - loss: 0.4713 - acc: 0.8950
Epoch 8/50
32/32 [==============================] - 0s 6ms/s